---
title: "Data"
---

- **Struffolino E.** (2023), **ISTAT absolute poverty thresholds and data report**, UNIMI Dataverse, Version 2.0.0, [access here](https://dataverse.unimi.it/dataset.xhtml?persistentId=doi:10.13130/RD_UNIMI/0UAGDY).

- Polizzi A., **Struffolino E.**, Van Winkle Z. (2022), **Systematic literature review on family demographic processes and in-work poverty**, Version 2.0.0. WZB Berlin Social Science Center. Dataset. [access here](https://doi.org/10.7802/2366).

- Gädecke M., **Struffolino E.**, Zagel H., Fasang A.F. (2021), **KOMPAKK - Essential occupations in Germany during the COVID-19 pandemic**. Version 1.0.0. SowiDataNet|datorium. Dataset - [access here](https://doi.org/10.7802/2283).

- Gädecke M., **Struffolino E.**, Zagel H., Fasang A.F. (2021), **KOMPAKK index of occupantions’ teleworkability in Germany**, Version 1.1.0. SowiDataNet|datorium. Dataset - [access here](https://doi.org/10.7802/2286).

- Gädecke M., Zagel H., **Struffolino E.**, Fasang A.F. (2021), **KOMPAKK index of economic sectors closure during the first wave of COVID-19**, Version 1.0.0. SowiDataNet|datorium. Dataset - [access here](https://doi.org/10.7802/2247).

- Gädecke M., **Struffolino E.**, Zagel H. (2020), **Family planning centres and doctors’ conscientious objection in Italy: Historical series by region**, Version 1.0.0. SowiDataNet|datorium. Dataset - [access here](https://doi.org/10.7802/1.2031).

