---
title: "Dissemination"
---

<span style="color: #FF4785;">**2024**</span>

  * **Struffolino E.**, Rowold C., Fasang A. (2024), [**I divari di genere non finiscono mai: la disuguaglianza pensionistica di genere i Italia e in Germania**](https://eticaeconomia.it/i-divari-di-genere-non-finiscono-mai-la-disuguaglianza-pensionistica-di-genere-in-italia-e-in-germania/), MENABÒ n.218.


  * **Struffolino E.** (2024), [**Le pensioni delle donne, tra carriere interrotte e ricompense diseguali**](https://naspread.eu/it/contributi-it/articoli-it/le-pensioni-delle-donne-tra-carriere-interrotte-e-ricompense-diseguali.html), Napsread.eu.

<span style="color: #FF4785;">**2023**</span>

- Festival dell’economia, presentation “Lavoratori poveri e salario minimo” with I.Marx (Università di Anversa), organized by P.Barbieri (Università di Trento), Trento, 27 maggio 2023
    * Media outreach: newspaper article by M.C. De Cesari, Il Sole 24 Ore “Salario minimo per i lavoratori poveri”, 28.05.2023.
    
    
- Presentation: “Il lavoro, un diritto. Qualità del lavoro, salario minimo, disoccupazione, povertà lavorativa” organized by PD Città di Rimini, title: “Il lavoro povero in Italia. Evidenze empiriche e proposte di policy”, 21.10.2023.

<span style="color: #FF4785;">**2022**</span>

  * Garnero A., Ciucciovino S., Magnani M., Naticchioni P., Raitano M., Scherer S., **Struffolino E.** (2022), [**In-work poverty: che fare?**](https://archivio.eticaeconomia.it/in-work-poverty-che-fare/), *Menabò di Etica & Economia*, 31.1.2022.  

  * Garnero A., Ciucciovino S., Magnani M., Naticchioni P., Raitano M., Scherer S., **Struffolino E.** (2022), [**In-work poverty: che fare?**](https://www.lavoce.info/archives/92886/cinque-proposte-contro-la-poverta-lavorativa/), *Lavoce.info*, 31.1.2022.  

  * Outreach di Garnero A., Ciucciovino S., Magnani M., Naticchioni P., Raitano M., Scherer S., **Struffolino E.** (2022), **Relazione del gruppo di lavoro sugli interventi e le misure di contrasto alla povertà lavorativa in Italia**, Gruppo di lavoro “Interventi e misure di contrasto alla povertà lavorativa” istituito con Decreto Ministeriale n. 126 
    * 	Intervista per quotidiano il manifesto, [**“Contro il lavoro povero serve sinergia di strumenti”**](https://ilmanifesto.it/contro-il-lavoro-povero-serve-sinergia-di-strumenti ), 20.01.2022. 
    * 	Intervista per il bi-settimanale L’Eco del Chisone, **“Da Piossasco al Ministero, studio sulla povertá”**, 23.02.2022.

  * **Struffolino E.**  – con Garnero A., Ciucciovino S., Magnani M., Naticchioni P., Raitano M., Scherer S. (2022), [**Un mix di politiche per contrastare il lavoro povero**](https://welforum.it/un-mix-di-politiche-per-contrastare-il-lavoro-povero/ ), Welforum.it, 01.12.2022. 
    *	Ripubblicato in “Una questione politica (e di relazioni industriali): il salario minimo in Italia e in Europa", curatore M. Jessoula, Social Cohesion Papers 1/2023, Osservatorio Internazionale per la coesione e l'inclusione sociale - *OCIS e Welforum.it*.
    * Outreach di Borgna C., **Struffolino E.** (2022), **Una scuola diseguale**, *Il Mulino*, Vol. 4 “L’Italia dei divari”: intervista rilasciata per il quotidiano La Repubblica, “La scuola italiana non supera la prova delle diseguaglianze”, 17.11.2022.

<span style="color: #FF4785;">**2021**</span>

  * **Struffolino E.**, Zagel H., Gädecke M. (2021), **Il lavoro in Germania durante la prima ondata della pandemia da Covid-19: chiusure e differenze di genere**, *Menabò di Etica & Economia* 147 - 31.3.2021.

  * Zagel H., **Struffolino E.**, Gädecke M. (2021), **Wirtschaftszweige im Lockdown während der ersten Welle der Covid-19 Pandemie: ein Vergleich zwischen den Bundesländern**, *FIS Briefing*, N.17.

  * Zagel H., **Struffolino E.**, Gädecke M. (2021), **Sectors in lockdown in the first wave of the Covid-19 pandemic across federal states in Germany**, *KOMPAKK Interim Report* - March 2021.

<span style="color: #FF4785;">**2020**</span>

  * Fasang A., Gädecke M., **Struffolino E.** and Zagel H. (2020), **Compensation and accumulation of economic risk during the COVID-19 pandemic A research project to understand the role of households and social policy in East and West Germany**,  “Sozialpolitik” *WZB-Mitteilungen* Nr. 170.

  * Borri G. and Struffolino E. (2020), **Politiche di sostegno al reddito in Germania durante l’emergenza COVID-19: poteva andare peggio, ma anche molto meglio**, *Menabò di Etica & Economia* 120 - 30.06.2020.

  * Borgna C. and Struffolino E. (2020), **Arbeitsmarktrisiko Geschlecht In Italien haben es Mädchen nach dem Schulabbruch besonders schwer** [Gendered risks in the labor market in italy, girls have a particularly hard time after leaving school], “Legitimität” *WZB-Mitteilungen* Nr. 167.

  * **Struffolino E.** and Borgna C. (2020), **Chi è stato davvero “lasciato indietro”? Le differenze di genere nell’integrazione dei giovani scarsamente istruiti nel mercato del lavoro**, *Menabò di Etica & Economia* 117 - 2.2.2020.

<span style="color: #FF4785;">**2019**</span>

  * **Struffolino E.** and Zagel H. (2019), **30 years of inequalities. Family planning centers in Italy**, *inGenere.it - Dati, Politiche, Questioni di Genere* - 10.10.2019.

  * Devillanova C., Raitano M., and **Struffolino E.** (2019), **Lavoro e salute: l’importanza di considerare le traiettorie di carriera**, in *Neodemos.info – Popolazione societá e politica* - 23.07.2019.

<span style="color: #FF4785;">**2018**</span>

  * **Struffolino E.** and Van Winkle Z. (2018), **Lavoratrici ma povere**, *inGenere - Dati, Politiche, Questioni di Genere* 6/12/2018.

  * Larenza O. and **Struffolino E.** (2018), **Perchè il ddl Pillon non è una buona idea**, *inGenere - Dati, Politiche, Questioni di Genere* 11/10/2018.

<span style="color: #FF4785;">**2017**</span>

  * Borgna C. and **Struffolino E.** (2017), **Schule und das Push’n Pull Vorzeitiger Schulabgang unter Mädchen und Jungen in Italien** [Fattori push e pull dell’abbandono scolastico tra ragazze e ragazzi in Italia], in ”Digital Wie Arbeit, Leben, Forschung sich und uns verändern”, *WZB-Mitteilungen* Nr. 155.
    
<span style="color: #FF4785;">**2016**</span>

  * **Struffolino E.** (2016), **Mehrfach benachteiligt. Wie Bildung, Job und Einkommen die Gesundheit alleinerziehender Mütter in der Schweiz prägen** [Svantaggi multipli. In che modo il titolo di studio, la partecipazione al mercato del lavoro e il reddito influenzano la salute delle madri sole in Svizzera], in ”Familie 2016. Arbeit, Gesundheit und Partnerschaft im Kontext”, *WZB-Mitteilungen* Nr. 153.
    
  * **Struffolino E.**, Bernardi L., Voorpostel M. (2016), **Selbstberichteter Gesundheitszustand, Erwerbstatus und Bildungsniveau alleinerziehender Mütter** [Salute, reddito e livello di istruzione delle madri sole], *SKBF - Schweizerische Koordinationsstelle für Bildungsforschung*.

  * **Struffolino E.**, Bernardi L. (2016), **One-parent households in Switzerland: Continuity and change over time**, in *Demos - Demographic information, ”Family, migration”* - No. 1 Giugno 2016 , Neuchâtel: Swiss Federal Statistical Office.

  * Filandri M., **Struffolino E.** (2016), **Proprietà della casa e riproduzione delle disuguaglianze nella Legge di Stabilità per il 2016**, *Menabò di Etica & Economia* 38, 29.2.2016.

<span style="color: #FF4785;">**2015**</span>

  * **Struffolino E.**, Filandri M. (2015), **Accumulare povertà? Note sul Report dell’ISTAT “La povertà in Italia 2014”**, *Menabò di Etica & Economia* 27, 30.7.2015.

  * Borgna C., Fanfani B., Mandrone E., Radicchia D., and **Struffolino E.** (2015), **Così uguali, così diversi**, *nelMerito.com*, 1.10.2015.

  * **Struffolino E.**, Borgna C (2015), **L’abbandono scolastico in Italia: genere, risorse familiari e mercato del lavoro**, *Menabò di Etica & Economia* 16, 16.2.2015.

