---
title: "Pubblications"
---

<span style="color: #FF4785;">**ARTICLES IN PEER-REVIEWED JOURNALS**</span>

- Fauser S., **Struffolino E.**, Levanon A. (2024 - forthcoming), [**Converging mothers’ employment trajectories between East and West Germany? A focus on the 2008-childcare-reform,**](), *Journal of Marriage and Family*. Open access. [Replication files]().

- Zagel H., **Struffolino E.** (2024 - forthcoming), [**Crisis-proof households? How social policy responses to the Covid-19 pandemic imagined work and care in Germany**](), *Journal of Social Policy*. Open access. [Replication files]().

- Hornung M., **Struffolino E.**, Zagel H. (2024 - forthcoming), [**Poverty among migrant, mixed, and non-migrant households:  the role of non-teleworkability and single-earnership in Germany**](), *Journal of Ethnic and Migration Studies*. Open access. [Replication files]().

- Piccarreta R., **Struffolino E.** (2024), [**Tools for analysing fuzzy clusters of sequences data**](10.4054/DemRes.2024.51.16), *Demographic Research*, vol. 51(1), pp.553-576. Open access. [Replication files](https://www.demographic-research.org/articles/volume/51/16/).

- Rowold C., **Struffolino E.**, Fasang A. (2024), [**Life-course-sensitive analysis of group inequalities: Combining Sequence Analysis with the Kitagawa-Oaxaca-Blinder decomposition**](https://doi.org/10.1177/00491241231224226). *Sociological Methods and Research*, online first. Open access. [Replication files](https://osf.io/ke3mg/).

- Piccarreta R., **Struffolino E.** (2024), [**Identifying and qualifying deviant cases in clusters of sequences: The why and the how**](https://doi.org/10.1007/s10680-023-09682-3), *European Journal of Population*, vol. 40(1). Open access. [Replication files](https://github.com/raffaellapiccarreta/Deviant-sequences-why-and-how).

- Fasang A.E., **Struffolino E.**, Zagel H. (2023), [**Household-level Prevalence and Poverty Penalties of Working in Non-teleworkable and Non-essential Occupations: Evidence from East and West Germany in 2019**](https://doi.org/10.1515/zsr-2022-0107), *Zeitschrift für Sozialreform – Journal of Social Policy Research*, vol.  69(2), pp. 85–117, . Open access. [Replication files](https://osf.io/kvqm7/).

- Ritschard G., Liao T.F., **Struffolino E.** (2023), [**Strategies for Multidomain Sequence Analysis in Social Research**](https://doi.org/10.1177/00811750231163833), *Sociological Methodology*, vol. 53(2), pp. 288–322. Open access.

- **Struffolino E.** and Van Winkle Z., (2023), [**Research note: The persistent risk of in-work poverty following the birth of a first, second, and third child across the life course**](https://doi.org/10.20377/jfr-910), *Journal of Family Research*, Vol. 35, pp. 345-356. Open access. [Replication files](https://ubp.uni-bamberg.de/jfr/index.php/jfr/article/view/910).

- Garnero A., Ciucciovino S., Magnani M., Naticchioni P., Raitano M., Scherer E., **Struffolino E.** (2022), [**Interventi e misure di contrasto alla povertà lavorativa in Italia**](https://www.rivisteweb.it/doi/10.7384/107275), *Economia & Lavoro - Rivista di politica sindacale, sociologia e relazioni industriali*, Vol. 3, pp. 9-32.

- Liao T.F., Bolano D., Cornwell B., Brzinsky-Fay C., Fasang A.E., Helske S., Piccarreta R., Raab M., Ritschard R., **Struffolino E.**, Studer M. (2022), [**Sequence analysis: Its past, present, and future**](https://doi.org/10.1016/j.ssresearch.2022.102772), *Social Science Research*, Vol.107, 102772. Open access.

- Polizzi A., **Struffolino E.**, Van Winkle Z. (2022), [**Family-demographic processes and in-work poverty: A systematic review**](https://doi.org/10.1016/j.alcr.2022.100462), *Advances in Life Course Research*, Vol. 52, 100462. [Pre-print](https://osf.io/preprints/socarxiv/zncaq).

- Kapelle N., Nutz T., Tisch D., Schechtl M., Lersch P., **Struffolino E.** (2022), [**My wealth, (y)our life satisfaction? Sole and joint wealth ownership and life satisfaction in marriage**](https://doi.org/10.1007/s10680-022-09630-7), *European Journal of Population*, vol. 38, pp. 811–834. Open access. [Replication files](https://osf.io/4mvxr/). 

- Lersch P., **Struffolino E.**, Vitali A. (2022), [**Introduction to the Special Issue “Wealth in couples”**](https://doi.org/10.1007/s10680-022-09640-5), *European Journal of Population* – Special Issue, vol. 38, pp. 623–641. Open access.

- **Struffolino E.**, Zagel H. (2021), [**Limited detraditionalization of intimacy: Growing socioeconomic differences in contraceptive use at first intercourse in Italy**](https://doi.org/10.1016/j.alcr.2021.100416), *Advances in Life Course Research*, Vol. 49, 100416. Pre-print.

- **Struffolino E.**, Van Winkle Z. (2021), [**Gender and race differences in pathways out of in-work poverty in the US**](https://doi.org/10.1016/j.ssresearch.2021.102585), *Social Science Research*, Vol. 99, 102585. [Pre-print](https://osf.io/preprints/socarxiv/dxc6n).

- Kailaheimo-Lönnqvist S., Fasang A., Jalovaara M., **Struffolino E.** (2021), [**Is parental divorce homogamy associated with a higher risk of separation from cohabitation and marriage?**](https://doi.org/10.1215/00703370-9489802), *Demography*, Vol. 58 (6), pp. 2219–2241. Open access. 

- Filandri M., **Struffolino E.** (2021), [**Povertà e ricchezza tra le famiglie di lavoratori in Italia: trent’anni di svantaggio cumulativo**](10.3280/SL2021-161006), *Sociologia del lavoro* – Special Issue n. 161 (3), pp. 97-121. 

- Filandri M., Morlicchio E., **Struffolino E.** (2021), [**Povertà, lavoro e famiglia: una riflessione introduttiva**](10.3280/SL2021-161002), *Sociologia del lavoro* – Special Issue n. 161 (3), pp. 27-33.

- **Struffolino E.**, Raitano M. (2020), [**Early-career complexity before and after labour-market deregulation in Italy: Heterogeneity by gender and socio-economic status across cohorts**](https://doi.org/10.1007/s11205-020-02373-0), *Social Indicators Research*, Vol. 151, pp. 231–257.

- **Struffolino E.**, Bernardi L., Larenza O. (2020), [**Lone parenthood and employment trajectories: A longitudinal mixed-method study**](https://doi.org/10.12765/CPoS-2020-14), *Comparative Population Studies*, Vol. 45.

- **Struffolino E.**, Borgna, C. (2020), [**Who is really left behind? Gender differences in the school-to-work transition of low-skilled youth in Italy**](https://doi.org/10.1080/13676261.2020.1713308), *Journal of Youth Studies*, 24:2, 162-185.

- **Struffolino E.**, Zaccaria, D. (2020), [**Did You Realize your Preferences for Early Retirement? Insights on the Agency-Within-Structure Mechanism across Welfare Regimes**](https://www.rivisteweb.it/doi/10.1424/96439), *Polis - Ricerche e studi su societá e politica*, Vol. 34, pp. 33-58. [Pre-print](https://www.econstor.eu/bitstream/10419/232578/1/Full-text-article-Struffolino-et-al-Did-you-realize.pdf).

- Raab M., **Struffolino E.** (2020), [**The heterogeneity of partnership trajectories to childlessness in Germany**](https://doi.org/10.1007/s10680-019-09519-y), *European Journal of Population*, Vol. 36, pp.53–70.

- Pasqua S., Filandri M., **Struffolino E.** (2020), [**Being working poor or feeling working poor? The role of work intensity and job stability for subjective poverty**](https://doi.org/10.1007/s11205-019-02174-0), *Social Indicators Research*, Vol. 147, pp. 781-803.

- Borgna, C., **Struffolino E.** (2019), [**Tempi difficili. Le condizioni occupazionali degli early school leavers in Italia prima e dopo la crisi**](10.3280/SL2019-155009), *Sociologia del Lavoro*, Vol.155, pp. 179-199. [Post-print](https://www.econstor.eu/bitstream/10419/227565/1/Full-text-article-Borgna-et-al-Tempi-difficili.pdf).

- **Struffolino E.** (2019), [**Navigating the early career: The social stratification of young workers’ employment trajectories in Italy**](https://doi.org/10.1016/j.rssm.2019.100421), *Research on Social Stratification and Mobility*, Vol. 63. 

- Devillanova C., Raitano M., **Struffolino E.**, (2019), [**Multiple life-course employment trajectories and health: Evidence from linked administrative and survey data**](https://www.demographic-research.org/articles/volume/40/47), *Demographic Research*, Vol. 40(47), pp.1375–1412.

- Filandri M., **Struffolino E.** (2019), [**Individual and household in-work poverty in Europe: Understanding the role of labor market characteristics**](https://doi.org/10.1080/14616696.2018.1536800), *European Societies*, Vol 21 (1), pp.130–157. 

- Filandri M., **Struffolino E. (2018)**, [**Lavoratori o lavoratrici povere? Disuguaglianze di genere nel mercato del lavoro in Europa**](https://www.francoangeli.it/Riviste/SchedaRivista.aspx?IDArticolo=63275&idRivista=53), *Sociologia e Ricerca Sociale*, Vol. 17, pp. 67-85. [Pre-print](https://www.econstor.eu/bitstream/10419/216741/1/Full-text-article-Filandri-et-al-Lavoratori-o%20lavoratrici.pdf).

- **Struffolino E.**, Raitano M. (2018), [**Il generation gap nell’accesso al mercato del lavoro: complessità e destandardizzazione delle traiettorie di ingresso**](https://www.futura-editrice.it/prodotto/il-divario-generazionale-nellaccesso-al-mercato-del-lavoro-differenziazione-e-destandardizzazione-delle-traiettorie-dingresso/), *Rivista delle Politiche Sociali*, Vol. 3, pp. 63-83. [Pre-print](https://www.econstor.eu/bitstream/10419/216742/1/Full-text-article-Struffolino-et-al-Il-divario-generazionale.pdf).

- Van Winkle Z., **Struffolino E.** (2018), [**When Working Isn’t Enough: Family Demographic Processes and In-Work Poverty across the Life Course in the United States**](https://www.demographic-research.org/articles/volume/39/12/), Demographic Research, Vol. 39 (12), pp. 365-380.

- Studer M., **Struffolino E.**, Fasang A. (2018), [**Estimating the relationship between time-varying covariates and trajectories: The Sequence Analysis Multistate Model Procedure**](https://doi.org/10.1177/008117501774712), *Sociological Methodology*, Vol. 48.

- Borgna C., **Struffolino E.** (2017), [**Pushed or pulled? Girls and boys facing early school leaving risk in Italy**](https://doi.org/10.1016/j.ssresearch.2016.06.021), *Social Science Research*, Vol.61, pp. 298–313.

- **Struffolino E.**, Bernardi L. (2017), [**Vulnerabilität alleinerziehender Mütter in der Schweiz aus einer Lebensverlaufsperspektive**](https://www.beltz.de/fachmedien/erziehungswissenschaft/zeitschriften/zeitschrift_fuer_soziologie_der_erziehung_und_sozialisation/artikel/36011-vulnerabilitaet-alleinerziehender-muetter-in-der-schweiz-aus-einer-lebensverlaufsperspektive.html) [La vulnerabilità delle madri sole in Svizzera dalla prospettiva del corso di vita], *ZSE Zeitschrift für Soziologie der Erziehung und Sozialisation* (2), pp. 123-141.

- **Struffolino E.**, Studer M., Fasang E. A. (2016), [**Gender, education, and family life courses in East and West Germany: Insights from new sequence analysis techniques**](https://doi.org/10.1016/j.alcr.2015.12.001), *Advances in Life Course Research*, 29, pp. 66-79.

- **Struffolino E.**, Bernardi L., Voorpostel M. (2016), [**Self-reported health among lone mothers in Switzerland: Do employment and education matter?**](https://doi.org/10.3917/popu.1602.0193), *Population-E*, Vol.71 (2), pp. 187-214.

- Filandri M., **Struffolino E.** (2013), [**Working poor: lavoratori con basso salario o occupati che vivono in famiglie povere? Un’analisi del fenomeno in Italia prima e dopo la crisi**](https://www.francoangeli.it/riviste/SchedaRivista.aspx?doi=10.3280/SL2013-131012), *Sociologia del Lavoro*, 131, pp.190-205.

- Raitano M., **Struffolino E.** (2013), [**Traiettorie lavorative e salariali a inizio carriera in Italia: uno studio longitudinale**](https://www.rivisteweb.it/doi/10.1425/75011), *Stato e Mercato*, 3, pp. 389-422. Post-print(https://www.econstor.eu/bitstream/10419/216744/1/Full-text-article-Raitano-et-al-Traiettorie-lavorative-a.pdf).

<span style="color: #FF4785;">**BOOKS**</span>

- Raab M., **Struffolino E.**, (2022) [**Sequence Analysis**](https://us.sagepub.com/en-us/nam/sequence-analysis/book272086), SAGE *“Quantitative Applications in the Social Sciences”* Series, Vol. 190.

<span style="color: #FF4785;">**BOOK CHAPTERS (with peer-review)**</span>

- Borgna C., **Struffolino E.** (2022), [**Una scuola diseguale**](10.1402/105277), *Il Mulino*, vol. 4, pp.87-95. 

- Borgna C., **Struffolino E.** (2018), [**Unpacking configurational dynamics: Sequence analysis and qualitative comparative analysis as a mixed-method design**](https://doi.org/10.1007/978-3-319-95420-2_17), in Studer M. and Ritschard G. (Eds.) in *“Sequence Analysis and Related Approaches”*. Life Course Research and Social Policies, Vol. 10, pp. 167-184. Springer, Cham. 

- **Struffolino E.**, Mortelmans D. (2018), [**Lone mothers in Belgium: Labour force attachment and risk factors**](https://link.springer.com/chapter/10.1007/978-3-319-63295-7_12), in Bernardi L. and Mortelmans D. (Eds.) *“Lone parenthood in the life course”*, Life Course Research and Social Policies Series, Vol. 8, pp. 257-282, Springer, Cham. 

- Milewski N., **Struffolino E.**, Bernardi L. (2018), [**Migrant status and lone motherhood at a glance: Patterns of female labor market participation in Switzerland**](https://link.springer.com/chapter/10.1007/978-3-319-63295-7_7), in Bernardi L. and Mortelmans D. (Eds.) *“Lone parenthood in the life course”*, Life Course Research and Social Policies Series, Vol. 8, pp. 141-163, Springer, Cham.

<span style="color: #FF4785;">**SPECIAL ISSUES**</span>

- Lersch P., **Struffolino E.**, Vitali A. (2022), [**Wealth in couples**](https://link.springer.com/article/10.1007/s10680-022-09640-5), *European Journal of Population* – Special Issue.

- Filandri M., Morlicchio E., **Struffolino E.** (2021), [**Povertà, lavoro e famiglia: prospettive di analisi dell’in-work poverty**](https://www.francoangeli.it/riviste/rivista-fascicolo?IDRivista=83&lingua=It&anno=2021), *Sociologia del lavoro* – Special Issue, n. 161 (3).

<span style="color: #FF4785;">**RESEARCH REPORTS and WORKING PAPERS**</span>

- Garnero A., Ciucciovino S., Magnani M., Naticchioni P., Raitano M., Scherer S., **Struffolino E.** (2022), [**Relazione del gruppo di lavoro sugli interventi e le misure di contrasto alla povertà lavorativa in Italia**](https://www.lavoro.gov.it/priorita/Documents/Relazione-del-Gruppo-di-lavoro-sugli-Interventi-e-misure-di-contrasto-alla-poverta-lavorativa-in-Italia.pdf), Gruppo di lavoro “Interventi e misure di contrasto alla povertà lavorativa” istituito con Decreto Ministeriale n. 126. 

- Borgna C., **Struffolino E.** (2014), [**Early school leaving in Italy: The heterogeneity of gender effects**](https://www.researchgate.net/publication/277609098_Early_school_leaving_dynamics_in_Italy_The_heterogeneity_of_gender_effects), Roma,ISFOL - *Isfol Research Paper*, 20.
