---
title: "Teaching"

format:
  html:
    page-layout: full
    toc: true
    
---

<span style="color: #FF4785;">**Other trainings**</span>

- **Sequence analysis for the social sciences**

  - LIfBi and University of Bamberg, 2025.
  - GESIS Training Courses, yearly from 2018 to 2025 (planned). 
  - University of Michigan, Population Dynamics and Health Program, 2022.
  - INVEST, University of Turku, 2022.
  - Humboldt-Universität zu Berlin, 2020.
  - University of Trento, 2018.

<span style="color: #FF4785;">**Doctoral programs**</span>

- **Longitudinal and Multilevel Analysis for Social Research**, ESOL-NASP, Economic Sociology, Organization and Labor Studies - Network for the Advancement of Social and Political Studies, University of Milan, 2025, 2024.

- **Panel data analysis for the social sciences**, ESOL-NASP, Economic Sociology, Organization and Labor Studies - Network for the Advancement of Social and Political Studies, University of Milan, 2022, 2021.

<span style="color: #FF4785;">**Master programs**</span>

- **In-work poverty in Europe and in the US**, Humboldt-Universität zu Berlin, 2021.

- **Values and culture in European societies**, Freie Universität Berlin, 2020.

- **Data Analysis using Stata**, Freie Universität Berlin, 2020.

- **In-work poverty in Europe and in the US**, Freie Universität Berlin, 2020.

- **Gender Inequality in Education and Employment**, Humboldt-Universität zu Berlin, 2018.

- **Research design in the social sciences**, Humboldt-Universität zu Berlin, 2018.

- **In-work poverty in Europe: individual and family dynamics**, Humboldt-Universität zu Berlin, 2017.

- **Event-history analysis: an introduction**, Humboldt-Universität zu Berlin, 2017.

<span style="color: #FF4785;">**Bachelor programs**</span>

- **Sociologia dello sviluppo economico locale**, University of Milan, Scienze per la globalizzazione (GLO), 2023-2025.

- **Sistemi sociali comparati**, University of Milan, Scienze internazionali e istituzioni europee (SIE), 2022.

- **Gender inequality in education and employment**, Humboldt-Universität zu Berlin, 2020.

- Tutorials of the lecture **Microsociology and demography** bz A.E. Fasang, Humboldt-Universität zu Berlin, 2015-2020.
