---
title: "In progress"
---

<span style="color: #FF4785;">**PAPERS**</span>

- **Struffolino E.**, Fauser S., **More childcare today, less poverty tomorrow? A county-level analysis on the effects of childcare availability on poverty in Germany.**, submitted.

- **Struffolino E.**, Fauser S., Fasang A., **How did the minimum wage implementation impact  mothers’ employment ? Evidence from Germany**, in progress.

- Hornung M., **Struffolino E., ** **Partnership constellation and poverty beyond the migrant/non-migrant dichotomy: an explorative gendered analysis in Germany**, R&R Journal of family research.

- **Struffolino E.**, Schechtl M., **Fiscal improverishment in Italy: A historical perspective**, in progress.

- Levanon A., **Struffolino E.**, Fauser S., Fasang A., **Poverty trajectories across time and space**, in progress

- Levanon A., **Struffolino E.**, Fasang A., Gomesky D., **Policy change and household labor supply: a survey experiment in Germany and Italy**, in progress

- **Struffolino E.**, Busetta A., Mendola D., Van Winkle Z., **Pensistency and intensity of poverty and health outcomes**, in progress 
